### ISSUE TITLE
RemoveAll does not remove one time listeners - curious as to why?

### ISSUE THREAD

**Issue by prodigga** [SixWays/Relay#1]
Hey there

In our game, everything is poolable. When an object returns to the pool, we RemoveAll on all the Relays managed by that object. 

I noticed that by default RemoveAll won't remove one time listeners. This is kind of unexpected.

Any reason for it being false by default?

Cheers!

**Comment by SixWays** [comment]
The thinking is that I see one-time listeners as being used fundamentally differently to persistent listeners, and as such expect them to be managed separately. There's also the expectation that, in most use cases, one-time listeners by their definition clean themselves up - although I recently added RemoveOnce to ensure all eventualities are covered.

That said, I'm open to the idea of make a (unfortunately breaking) change to that default if people feel strongly?

**Comment by prodigga** [comment]
It's kind of funny, because when I first looked at the library I thought that 'persistent listeners' were 'fundamentally different'. Because of the naming ('persistent'), I thought that RemoveAll wouldn't actually remove the persistent listeners. Because, you know, they are persistent! 😃 

That is actually what led me to look closer into what 'RemoveAll' actually does, and I was able to confirm that persistent listeners were being removed by default, but also noticed that one time listeners were not and that was really unexpected. 

I figured if I was calling RemoveAll on something that has had things added to it, that it would remove all the things that were added to it! And that's how I got here. :)

**Comment by SixWays** [comment]
Haha! Fair enough, I guess there's a bit of a lack of clarity there. Perhaps I need to revisit some naming conventions...

**Comment by prodigga** [comment]
It might bloat the API a bit too much, but maybe 3 methods, forcing the user to specify in an attempt to stop existing code from breaking:

```
RemoveAllPersistant() => RemoveAll(false,true);
RemoveAllOnce() => RemoveAll(false,true);
RemoveAll(bool removePersistant, bool removeOnce); //User must be explicit
[Obsolete]
RemoveAll(); => RemoveAllPersistant(); //Attempt to prevent existing code from breaking
```

Not perfect though.. If I am honest, as a user I would must prefer to be able to call 'RemoveAll' and be done with it.. ie RemoveAll implementation would be:

```
RemoveAll() 
{
    RemoveAllPersistant();
    RemoveAllOnce();
}
```

Or, what I think we both had in mind:

```
RemoveAll(bool removePersistant = true, bool removeOnce = true) 
{
    if(removePersistant)
        RemoveAllPersistant();
    if(removePersistant)
        RemoveAllOnce();
}
```

I understand it is tricky since it does break existing code, but it would be something to do sooner rather than later.

Totally up to you my dude, for now I am just using my extension method 'relay.ActuallyRemoveAll()' 😃
